name: CI Build Check

on:
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the source code
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # 2. Set up a Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      # 3. Install dependencies for the entire workspace
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. Build flume-cli
      - name: Build flume-cli
        run: yarn workspace flume-cli build



